### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by Comicus** [Ravendwyr/TradeSkillInfo#10]
I got this error today upon logging in, not sure if TSI is causing it or just a conflict with WorldQuestTab, sent error to them also.

4x WorldQuestTab\WorldQuestTab-8.2.01d.lua:471: attempt to compare string with number
WorldQuestTab\WorldQuestTab-8.2.01d.lua:471: in function <WorldQuestTab\WorldQuestTab.lua:452>
[C]: in function `sort'
WorldQuestTab\WorldQuestTab-8.2.01d.lua:452: in function <WorldQuestTab\WorldQuestTab.lua:446>
WorldQuestTab\WorldQuestTab-8.2.01d.lua:1405: in function <WorldQuestTab\WorldQuestTab.lua:1384>
[C]: ?
...ns\TradeSkillInfo\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...ns\TradeSkillInfo\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...ns\TradeSkillInfo\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...ns\TradeSkillInfo\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...ns\TradeSkillInfo\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:450: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:569: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1210: in function <FrameXML\UIParent.lua:1108>

**Comment by EthanCentaurai** [comment]
Looking at the code of WorldQuestTab makes it look like an issue with their addon, specifically the World Quest filters. I don't think TSI is causing it but I'll keep an eye on it. Sorry. 😦
