### ISSUE TITLE
[Error] SetBackdrop

### ISSUE THREAD

**Issue by amiyuy** [Ravendwyr/TradeSkillInfo#16]
**Describe the bug**
When opening a tooltip of an item that TradeSkillInfo wants to modify, error happens.

**Expected behavior**
No error.

**WoW version**
Retail 9.0.1

**Additional context**
SetBackdrop has been moved/removed - https://wow.gamepedia.com/API_Frame_SetBackdrop

Error
```
Message: [string "TradeskillInfoFrame:OnLoad"]:1: attempt to call method 'SetBackdropColor' (a nil value)
Time: Sat Oct 17 15:11:26 2020
Count: 1
Stack: [string "TradeskillInfoFrame:OnLoad"]:1: attempt to call method 'SetBackdropColor' (a nil value)
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\AddOns\TradeSkillInfo\TradeskillInfo.lua"]:1606: in function `LoadUI'
[string "@Interface\AddOns\TradeSkillInfo\TradeskillInfo.lua"]:580: in function `Item_OnClick'
[string "@Interface\AddOns\TradeSkillInfo\TradeskillInfo.lua"]:566: in function <Interface\AddOns\TradeSkillInfo\TradeskillInfo.lua:565>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `ChatFrame_OnHyperlinkShow'
[string "*:OnHyperlinkClick"]:1: in function <[string "*:OnHyperlinkClick"]:1>

Locals: self = TradeskillInfoFrame {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = TradeskillInfoFrame {
 0 = <userdata>
}
(*temporary) = 0.050000
(*temporary) = 0.050000
(*temporary) = 0.050000
(*temporary) = 0.800000
(*temporary) = "attempt to call method 'SetBackdropColor' (a nil value)"
```

**Comment by b-morgan** [comment]
This error can be eliminated by changing line 204 of TradeskillInfoUI.xml from:
```
	<Frame name="TradeskillInfoFrame" toplevel="true" frameStrata="LOW" movable="true" resizable="true" parent="UIParent" enableMouse="true" hidden="true">
```
to:
```
	<Frame name="TradeskillInfoFrame" toplevel="true" frameStrata="LOW" movable="true" resizable="true" parent="UIParent" enableMouse="true" hidden="true" inherits="BackdropTemplate">
```
(add ` inherits="BackdropTemplate"`)

The actual backdrop isn't very pretty and I haven't figured out how to fix that, but at least things work again.

**Comment by Ravendwyr** [comment]
This was fixed in 6eb3a787ab2ef79ff95133f8d3e555479effd215

I haven't been actively maintaining this addon for a while but this should already be on CurseForge under the alpha channel.

**Comment by b-morgan** [comment]
I can't find the alpha that contains this fix on CurseForge. Can you provide a link in case I'm not looking in the right place.

**Comment by Ravendwyr** [comment]
This one's the most recent: https://www.curseforge.com/wow/addons/tradeskill-info/files/3123166

It's not up-to-date but it's better than nothing. :)

**Comment by b-morgan** [comment]
Thanks! I needed to click the "View All" button to see it.
